### ISSUE TITLE
memoryDriver not working

### ISSUE THREAD

**Issue by abarke** [RasCarlito/axios-cache-adapter#39] opened 2018-10-05 13:37 UTC
I tried the **localforage-memoryStorageDriver** on it's own using the example in the README.md as a base and it doesnt seem to work at all. If I swap it for the inbuilt drivers localforage.INDEXEDDB for example it works fine or do not specify the driver it uses the default drivers.

Can someone provide a fix or a working example?

**Comment by RasCarlito** [comment] 2018-10-08 07:15
Hi @abarke 

I'll try to take a look at what the problem is using the `localforage-memoryStorageDriver`. Did you see any particular error or was it just failing silently?

Cheers

**Comment by abarke** [comment] 2018-10-08 08:42
Thanks @RasCarlito it was failing silently.

**Comment by RasCarlito** [comment] 2018-10-08 13:17
Thanks for the info!

Can you tell me what version of `localforage` and `localforage-memoryStorageDriver` you are using?

**Comment by abarke** [comment] 2018-10-08 13:28
axios-cache-adapter 2.1.1
localforage 1.7.2
localforage-memoryStorageDriver 0.9.2

**Comment by RasCarlito** [comment] 2018-10-08 17:49
Hey @abarke ! I added a unit test to make sure it is continually tested.

I was able to make it work like this:

```js
import axios from 'axios'
import { setup } from 'axios-cache-adapter'

import localforage from 'localforage'
import memoryDriver from 'localforage-memoryStorageDriver'

async function exec () {
  // Define the memory driver in localforage
  await localforage.defineDriver(memoryDriver)

  // Create a localforage instance forcing the memory driver
  const store = localforage.createInstance({
    driver: memoryDriver._driver
  })

  // Create an axios instance with the cache adapter passing the created store
  const api = setup({
    cache: { store }
  })

  // Then just use the axios instance as you normally would
  const response = await api({
    method: 'get',
    url: 'https://httpbin.org/get'
  })

  console.log(response.status) // > 200

  // Get stored data from localforage directly
  const { data } = await store.getItem('https://httpbin.org/get')

  console.log(data.status) // > 200
}
```

Tell me if this works for you 😃

**Comment by RasCarlito** [comment] 2018-10-19 09:28
Yes it was missing. I think the way the memory driver integrates with `localforage` changed at some point 😅

**Comment by RasCarlito** [comment] 2018-12-19 10:09
Hi @abarke, just checking in with you if the localforage memory driver integration worked alright with you so that I can close this issue.

Thank you in advance for getting back to me 😄

**Comment by abarke** [comment] 2018-12-19 10:49
Sorry I didn’t manage to test it. I will have a look tonight. Thanks.

**Closed** 2019-01-15 07:18 UTC
Labels: bug
