### ISSUE TITLE
transformResponse behaviour

### ISSUE THREAD

**Issue by gonstr** [RasCarlito/axios-cache-adapter#28] opened 2018-03-11 23:14 UTC
When you supply a function to the axios transformResponse config, the function gets called both before the response gets cached, and when a response is retrieved from the cache later, which causes code like this to fail:

```js
const http = axios.create({ adapter: cache.adapter })

const callApi = () => http.get('https://abc.com/api', {
  transformResponse: [data => {
    return data.a + data.b
  }]
})

await callApi()
await callApi()
```

The two calls to callApi() will return different data since it runs transformResponse on the cached response. You need to write code like this for it to work:

```js
const http = axios.create({ adapter: cache.adapter })

const callApi = () => http.get('https://abc.com/api', {
  transformResponse: [data => {
    if (data.transformed) return data
    return { transformed: true, value: data.a + data.b }
  }]
})
```

It's great that you can transform a response before caching it but is there any way to get axios to not run transform again on already cached responses?

**Comment by RasCarlito** [comment] 2018-03-12 14:13
Hi @gonstr !

Thanks for using `axios-cache-adapter` :)

I haven't used the `transformResponse` functionnality of `axios` before so I wasn't aware of this. It should be possible!

I'll check in to it when I have time but if you find a solution it would be awesome if you submit a PR with the modifications.

Cheers

**Comment by RasCarlito** [comment] 2018-03-14 22:43
Nice digging around! :)

Well then I only see one solution.

We can wrap each `transformResponse` method to apply the kind of logic you showed in your first example but internally in `axios-cache-adapter` so that the final user doesn't have to.

Something like:

```js
config.transformResponse = config.transformResponse.map(transform => {
  return (data, header) => {
    if (data._transformed) return data

    data._tranformed = true

    return transform(data, header)
  }
})
```

This can probably be done directly in around [here](https://github.com/RasCarlito/axios-cache-adapter/blob/master/src/index.js#L24) in the `async adapter` method on the `reqConfig` object before data is retrieved from cache, or directly in the [`mergeRequestConfig`](https://github.com/RasCarlito/axios-cache-adapter/blob/master/src/config.js#L77) method which augments the `reqConfig` for the current request.

I think we can use an underscore to prefix the `tranformed` flag to prevent conflicts with actual data from the server, although maybe someone actually returns that key.
Else we could just add that to the `header` object to prevent data collision but we need to make sure it is being serialized in the [`response`](https://github.com/RasCarlito/axios-cache-adapter/blob/master/src/response.js#L4) method which is called right after awaiting the original adapter execution.

Again, thanks for helping out :)
If I'm unclear on anything don't hesitate to ping me.

Cheers

**Comment by RasCarlito** [comment] 2018-03-14 22:52
And sorry for the response delay @gonstr I wish I had more time to work on this, but priorities shift over time =/

**Comment by RasCarlito** [comment] 2018-03-14 23:02
Also I have just pushed a small commit to the master branch fixing linting issues

**Comment by RasCarlito** [comment] 2018-03-18 17:39
Hi @gonstr !

I've added a test for the `transformResponse` as you can see in [this PR](https://github.com/RasCarlito/axios-cache-adapter/pull/30/files) and the test actually passes!

I did have a problem at first because I set it up like in your example.

```js
const http = axios.create({ adapter: cache.adapter })

const callApi = () => http.get('https://abc.com/api', {
  transformResponse: [data => {
    return data.a + data.b
  }]
})

await callApi()
await callApi()
```

Running this code actually fails on the first `await callApi()` because `data` is a string and not an object.

The default `transformResponse` array contains the method which does a `JSON.parse()` on the data.

Explained in this issue: https://github.com/axios/axios/issues/430

To make it work we need to extend the default `transformResponse` like this:

```js
const http = axios.create({ adapter: cache.adapter })

const callApi = () => http.get('https://abc.com/api', {
  transformResponse: http.defaults.transformResponse.concat(
    [data => {
      return data.a + data.b
    }]
  )
})

await callApi()
await callApi()
```

This works as expected. The data is actually stored in the cache before the `tranformResponse` is applied. So when the data comes from the cache it is transformed correctly like the first time.

So I'm going to close this for now.

Cheers

**Comment by gonstr** [comment] 2018-03-18 21:10
Hi @RasCarlito 

I don't think you need to add the default transformResponse for it to get parsed to json. Maybe that's something they changed in later versions of axios? That pull request you referenced is quite old?

Also, I saw the test you added but I think because of race conditions you need to sometimes call the api more than twice to see the bug.

See this on runkit:

https://runkit.com/gonstr/axios-cache-adapter

It works the first two times you call the api but not the third time.

I tried working a bit on this bug a few days ago, trying to implement your suggested changes, wrapping all transformResponse functions, but I didnt get it to work. Might give it another chance but if you have time I'm sure you can fix it faster than me :)

Cheers

**Comment by RasCarlito** [comment] 2018-03-20 09:10
Right! Thanks for the example! Re-opening the issue

I'll try to work on it this week :)

**Comment by miluoshi** [comment] 2018-10-01 13:44
Any updates on this?

**Comment by RasCarlito** [comment] 2018-10-07 13:47
Hi @miluoshi! Sorry no updates on this so far. I haven't worked on the lib in a while. I did try this week to find the source of the bug. I am able to reproduce it but I still need to pin point the origin.

I got a few hours in the train ahead of me, will try to work this out.

Do you have a real use case where this problem occurs that you could share?

Cheers

**Comment by miluoshi** [comment] 2018-10-07 14:15
Thanks for the info!
My use case was that server returned response data wrapped in object property, ie.
```javascript 
{
  "elements": [...]
}```
and all I needed was the array inside the object, so I was using `transformResponse` to have these data unwrapped. However, in the cached response already unwrapped cached data are being passed to the same `transformResponse` again thus producing runtime error.

**Comment by RasCarlito** [comment] 2018-10-07 14:16
Ok so I found the culprit. Just posted #40 with the fix.

This fix is only applicable when `axios-cache-adapter` is used with its memory store. I don't think this would happen when using a `LocalForage` instance as store but I need to do some more testing to be sure.

**Comment by RasCarlito** [comment] 2018-10-07 14:17
Thanks for the extra info @miluoshi 

I think the PR I posted should fix your use case then 😄

**Closed** 2018-10-08 18:34 UTC
Labels: bug, help wanted

**Comment by RasCarlito** [comment] 2018-10-08 18:43
Will try to release this soon 😃 

My first solution was using the `cloneDeep` method from `lodash` when reading from the in memory store.

But then I changed my mind and instead of adding another external dependency I used `JSON.stringify()` when writing and `JSON.parse()` when reading.

Hope this is a satisfying solution. Problems would occur if the fetched data is not JSON but I would have had the same problem with `cloneDeep` I think.

@gonstr @miluoshi do you have a thought about this?

**Comment by miluoshi** [comment] 2018-10-08 19:13
@RasCarlito I think JSON.stringify/parse solution is valid. You can `JSON.stringify` any JS value (boolean, number, string, object, array). So if you store stringified value and ten get it back by parsing, no information is lost. 
As far as I know the only information lost by stringifying JS values is object's prototype, but it should not be a concern as object can be obtained from response data only by JSON.parse so it's just pure object.
